// resources/js/Pages/Quotes/Create.vue
<template>
  <AppLayout
    title="Nueva cotización"
    :breadcrumbs="[{ label: 'Cotizaciones', href: route('quotes.index') }, { label: 'Nueva cotización' }]"
  >
    <div class="mx-auto max-w-4xl">
      <form @submit.prevent="submit" class="space-y-6">

        <!-- Cabecera -->
        <div class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-100">
          <h2 class="mb-5 text-sm font-semibold text-gray-900">Información general</h2>
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div class="sm:col-span-2">
              <label class="block text-sm font-medium text-gray-700 mb-1.5">
                Cliente <span class="text-red-500">*</span>
              </label>
              <select v-model="form.client_id" :class="inputClass">
                <option value="">Seleccionar cliente...</option>
                <option v-for="c in clients" :key="c.id" :value="c.id">
                  {{ c.name }} — {{ c.rut }}
                </option>
              </select>
              <p v-if="form.errors.client_id" class="mt-1 text-xs text-red-600">{{ form.errors.client_id }}</p>
            </div>

            <div class="sm:col-span-2">
              <label class="block text-sm font-medium text-gray-700 mb-1.5">
                Título del proyecto/servicio <span class="text-red-500">*</span>
              </label>
              <input type="text" v-model="form.title" :class="inputClass"
                     placeholder="Ej: Desarrollo de sistema de gestión de inventario"/>
              <p v-if="form.errors.title" class="mt-1 text-xs text-red-600">{{ form.errors.title }}</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5">Moneda</label>
              <select v-model="form.currency" :class="inputClass">
                <option value="CLP">CLP — Peso chileno</option>
                <option value="USD">USD — Dólar</option>
              </select>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5">Válida hasta</label>
              <input type="date" v-model="form.valid_until" :class="inputClass" :min="today"/>
              <p v-if="form.errors.valid_until" class="mt-1 text-xs text-red-600">{{ form.errors.valid_until }}</p>
            </div>
          </div>
        </div>

        <!-- Ítems -->
        <div class="rounded-xl bg-white shadow-sm ring-1 ring-gray-100 overflow-hidden">
          <div class="flex items-center justify-between px-6 py-4 border-b border-gray-100">
            <h2 class="text-sm font-semibold text-gray-900">Ítems de la cotización</h2>
            <button type="button" @click="addItem"
                    class="inline-flex items-center gap-1.5 rounded-lg bg-indigo-50 px-3 py-1.5 text-xs font-medium text-indigo-700 hover:bg-indigo-100 transition-colors">
              <svg class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15"/>
              </svg>
              Agregar ítem
            </button>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full">
              <thead>
                <tr class="bg-gray-50 text-left text-xs font-semibold uppercase tracking-wider text-gray-400">
                  <th class="px-4 py-3" style="width:40%;">Descripción</th>
                  <th class="px-4 py-3" style="width:25%;">Detalle (opcional)</th>
                  <th class="px-4 py-3 text-center" style="width:10%;">Cant.</th>
                  <th class="px-4 py-3 text-right" style="width:15%;">Precio Unit.</th>
                  <th class="px-4 py-3 text-right" style="width:10%;">Subtotal</th>
                  <th class="px-4 py-3" style="width:5%;"></th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-50">
                <tr v-for="(item, i) in form.items" :key="i" class="group">
                  <td class="px-4 py-2.5">
                    <input v-model="item.description" type="text" :class="inputClass"
                           placeholder="Ej: Módulo de autenticación"/>
                    <p v-if="form.errors[`items.${i}.description`]" class="mt-1 text-xs text-red-600">
                      {{ form.errors[`items.${i}.description`] }}
                    </p>
                  </td>
                  <td class="px-4 py-2.5">
                    <input v-model="item.detail" type="text" :class="inputClass"
                           placeholder="Especificaciones adicionales"/>
                  </td>
                  <td class="px-4 py-2.5">
                    <input v-model.number="item.quantity" type="number" min="1" :class="inputClass + ' text-center'"/>
                  </td>
                  <td class="px-4 py-2.5">
                    <input v-model.number="item.unit_price" type="number" min="0" :class="inputClass + ' text-right font-mono'"
                           :placeholder="form.currency === 'CLP' ? '500000' : '1000'"/>
                  </td>
                  <td class="px-4 py-2.5 text-right font-mono text-sm font-semibold text-gray-700">
                    {{ formatAmount(item.quantity * item.unit_price) }}
                  </td>
                  <td class="px-4 py-2.5">
                    <button type="button" @click="removeItem(i)"
                            :disabled="form.items.length === 1"
                            class="rounded-md p-1.5 text-gray-300 hover:text-red-500 hover:bg-red-50 transition-colors disabled:opacity-30 disabled:cursor-not-allowed">
                      <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                      </svg>
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Totales -->
          <div class="flex justify-end border-t border-gray-100 px-6 py-4">
            <div class="w-64 space-y-2">
              <div class="flex justify-between text-sm text-gray-600">
                <span>Subtotal neto</span>
                <span class="font-mono font-semibold">{{ formatAmount(subtotal) }}</span>
              </div>
              <div class="flex justify-between text-sm text-gray-600">
                <span>IVA ({{ form.tax_rate }}%)</span>
                <span class="font-mono font-semibold">{{ formatAmount(taxAmount) }}</span>
              </div>
              <div class="flex justify-between rounded-lg bg-indigo-600 px-3 py-2 text-white">
                <span class="font-semibold">Total</span>
                <span class="font-mono font-bold">{{ formatAmount(total) }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Notas y términos -->
        <div class="rounded-xl bg-white p-6 shadow-sm ring-1 ring-gray-100">
          <h2 class="mb-5 text-sm font-semibold text-gray-900">Notas y términos</h2>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5">
                Notas para el cliente
              </label>
              <textarea v-model="form.notes" rows="3" :class="inputClass + ' resize-none'"
                        placeholder="Información adicional que quieras compartir con el cliente..."/>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1.5">
                Términos y condiciones
              </label>
              <textarea v-model="form.terms" rows="4" :class="inputClass + ' resize-none'"
                        placeholder="Condiciones de pago, plazos, garantías..."/>
            </div>
          </div>
        </div>

        <div class="flex items-center justify-end gap-3">
          <Link :href="route('quotes.index')"
                class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors">
            Cancelar
          </Link>
          <button type="submit" :disabled="form.processing"
                  class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 transition-colors disabled:opacity-60">
            {{ form.processing ? 'Guardando...' : 'Crear cotización' }}
          </button>
        </div>
      </form>
    </div>
  </AppLayout>
</template>

<script setup>
import { computed } from 'vue';
import { Link, useForm } from '@inertiajs/vue3';
import AppLayout from '@/Layouts/AppLayout.vue';

const props = defineProps({
  clients:      Array,
  defaultTerms: String,
});

const inputClass = 'w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500/20';
const today = new Date().toISOString().split('T')[0];

const form = useForm({
  client_id:   '',
  title:       '',
  currency:    'CLP',
  tax_rate:    19,
  tax_included: false,
  valid_until: '',
  notes:       '',
  terms:       props.defaultTerms ?? '',
  items: [
    { description: '', detail: '', quantity: 1, unit_price: 0 },
  ],
});

const subtotal = computed(() =>
  form.items.reduce((sum, item) => sum + (item.quantity || 0) * (item.unit_price || 0), 0)
);

const taxAmount = computed(() =>
  Math.round(subtotal.value * (form.tax_rate / 100))
);

const total = computed(() => subtotal.value + taxAmount.value);

function formatAmount(amount) {
  if (form.currency === 'USD') {
    return 'USD ' + Number(amount).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  }
  return '$' + new Intl.NumberFormat('es-CL').format(amount);
}

function addItem() {
  form.items.push({ description: '', detail: '', quantity: 1, unit_price: 0 });
}

function removeItem(index) {
  if (form.items.length > 1) form.items.splice(index, 1);
}

function submit() {
  form.post(route('quotes.store'));
}
</script>

// resources/js/pages/quotes/create.tsx
import AppLayout from '@/layouts/app-layout'
import { quotes } from '@/routes';
import { BreadcrumbItem } from '@/types';
import { Head, router, useForm, usePage } from '@inertiajs/react'
import { Label } from '@radix-ui/react-label';
import ReactSelect, { CSSObjectWithLabel } from 'react-select';

// import { useEffect, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Textarea } from "@/components/ui/textarea"
import { useState } from 'react';


const breadcrumbs: BreadcrumbItem[] = [
    {
        title: "Crear Cotización",
        href: quotes().url,
    },
];

type Client = {
    id: number;
    name: string;
};

const CreateQuote = () => {
    // Formateador de CLP
    const formatCLP = (value: string | number) => {
        const num = Number(value);
        if (isNaN(num)) return '';
        return num.toLocaleString('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 });
    };
    // Estado para descuento e impuestos
    const [discount, setDiscount] = useState<number>(0); // porcentaje
    const [tax, setTax] = useState<number>(0); // porcentaje

   
    const { data, setData, post, errors, processing } = useForm({
        client_id: '',
        title: '',
        description: '',
        total_amount: '',
        delivery_date: '',
        quote_items: [
            { quantity: 1, description: '', unit_price: '', total: '' },
        ],
    });

     // Calcular subtotal
    const subtotal = data.quote_items.reduce((acc, item) => acc + (Number(item.total) || 0), 0);
    // Calcular total con descuento e impuestos
    const discountAmount = subtotal * (discount / 100);
    const taxedAmount = (subtotal - discountAmount) * (tax / 100);
    const total = subtotal - discountAmount + taxedAmount;

    // Funciones para manejar items
    const handleItemChange = (idx: number, field: string, value: string | number) => {
        const items = [...data.quote_items];
        items[idx] = {
            ...items[idx],
            [field]: value,
        };
        // Calcular total automáticamente
        if (field === 'quantity' || field === 'unit_price') {
            const qty = Number(items[idx].quantity) || 0;
            const price = Number(items[idx].unit_price) || 0;
            items[idx].total = (qty * price).toFixed(2);
        }
        setData('quote_items', items);
    };

    const addItem = () => {
        setData('quote_items', [
            ...data.quote_items,
            { quantity: 1, description: '', unit_price: '', total: '' },
        ]);
    };

    const removeItem = (idx: number) => {
        const items = [...data.quote_items];
        items.splice(idx, 1);
        setData('quote_items', items);
    };

    const { clients } = usePage().props as unknown as { clients: Client[] };

    const submitForm = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        post("/quotes", {
            onSuccess: () => {
                // Manejar el éxito, como redirigir o mostrar un mensaje
                console.log("Cotización creada con éxito");
            },
            onError: () => {
                console.log("Error al crear la cotización");
                // Manejar el error, como mostrar un mensaje de error
            },
        });
    };

    const selectStyles = {
        control: (provided: CSSObjectWithLabel) => ({
            ...provided,
            minHeight: '40px',
            height: '40px',
            boxShadow: 'none',
        }),
        valueContainer: (provided: CSSObjectWithLabel) => ({
            ...provided,
            height: '40px',
            padding: '0 8px',
        }),
        input: (provided: CSSObjectWithLabel) => ({
            ...provided,
            margin: '0px',
        }),
        indicatorsContainer: (provided: CSSObjectWithLabel) => ({
            ...provided,
            height: '40px',
        }),
    };
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Crear Cotización" />
            <div className="px-4 sm:p-6 lg:px-8">
                <h1 className="text-2xl font-semibold">Crear Nueva Cotización</h1>
            </div>
            <div className="px-4 sm:p-6 lg:px-8">
                {/* Formulario para crear una nueva cotización */}
                <form onSubmit={submitForm} className="flex flex-col w-full gap-6">
                    <div className="flex flex-col sm:flex-row w-full gap-4 mb-4">
                        <div className="flex flex-1 flex-col gap-2">
                            <Label htmlFor="title">Nombre de la Cotización</Label>
                            <Input
                                type="text"
                                id="title"
                                placeholder="Ej: Creación de ecommerce de ropa para empresa X"
                                value={data.title}
                                onChange={e => setData('title', e.target.value)}
                                required
                                style={{ height: '40px' }}
                            />
                            {errors.title && <span className="text-red-500 text-xs">{errors.title}</span>}
                        </div>
                        <div className="flex flex-1 flex-col gap-2">
                            <Label htmlFor="client_id">Cliente asociado</Label>
                            <ReactSelect
                                inputId="client_id"
                                name="client_id"
                                options={clients.map((client: Client) => ({ value: client.id, label: client.name }))}
                                value={clients.find((c: Client) => c.id === Number(data.client_id)) ? { value: Number(data.client_id), label: clients.find((c: Client) => c.id === Number(data.client_id))?.name } : null}
                                onChange={(option: { value: number; label: string | undefined } | null) => setData('client_id', option ? String(option.value) : '')}
                                placeholder="Selecciona un cliente"
                                isClearable
                                isSearchable
                                styles={selectStyles}
                            />
                            {errors.client_id && <span className="text-red-500 text-xs">{errors.client_id}</span>}
                        </div>
                    </div>
                    <div className="flex w-full flex-col gap-2 mb-4">
                        <Label htmlFor="description">Descripción General</Label>
                        <Textarea
                            id="description"
                            placeholder="Descripción de la cotización"
                            value={data.description}
                            rows={15}
                            style={{ minHeight: "130px" }}
                            onChange={e => setData('description', e.target.value)}
                            required
                        />
                        {errors.description && <span className="text-red-500 text-xs">{errors.description}</span>}
                    </div>

                    {/* Desglose de Servicios */}
                    <div className="w-full bg-muted/30 rounded-lg p-4 mb-4">
                        <h2 className="font-semibold mb-2">Desglose de Servicios</h2>
                        <div className="overflow-x-auto">
                            <table className="min-w-full text-sm border-separate border-spacing-y-2">
                                <thead>
                                    <tr className="text-muted-foreground">
                                        <th className="px-2 py-1 text-left">CANTIDAD</th>
                                        <th className="px-2 py-1 text-left">DESCRIPCIÓN</th>
                                        <th className="px-2 py-1 text-left">PRECIO UNIT.</th>
                                        <th className="px-2 py-1 text-left">TOTAL</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {data.quote_items.map((item, idx) => (
                                        <tr key={idx} className="bg-background border rounded">
                                            <td className="px-2 py-1">
                                                <Input
                                                    type="number"
                                                    min={1}
                                                    value={item.quantity}
                                                    onChange={e => handleItemChange(idx, 'quantity', Number(e.target.value))}
                                                    className="w-16"
                                                />
                                            </td>
                                            <td className="px-2 py-1">
                                                <Input
                                                    type="text"
                                                    value={item.description}
                                                    onChange={e => handleItemChange(idx, 'description', e.target.value)}
                                                    className="w-full"
                                                />
                                            </td>
                                            <td className="px-2 py-1">
                                                <div className="relative">
                                                    <Input
                                                        type="text"
                                                        inputMode="numeric"
                                                        pattern="[0-9]*"
                                                        value={item.unit_price !== '' ? formatCLP(item.unit_price) : ''}
                                                        onChange={e => {
                                                            // Eliminar todo lo que no sea número
                                                            let raw = e.target.value.replace(/[^\d]/g, '');
                                                            // Evitar ceros a la izquierda
                                                            if (raw.length > 1) raw = raw.replace(/^0+/, '');
                                                            handleItemChange(idx, 'unit_price', raw);
                                                        }}
                                                        className="w-24 pr-2 text-right"
                                                    />
                                                    <span className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-muted-foreground pointer-events-none">CLP</span>
                                                </div>
                                            </td>
                                            <td className="px-2 py-1 font-mono text-right align-middle">
                                                {Number(item.total).toLocaleString('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 })}
                                            </td>
                                            <td className="px-2 py-1">
                                                {data.quote_items.length > 1 && (
                                                    <button type="button" onClick={() => removeItem(idx)} className="text-red-500 hover:underline text-xs">Eliminar</button>
                                                )}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                        <button type="button" onClick={addItem} className="mt-2 px-3 py-1 rounded bg-primary/10 text-primary hover:bg-primary/20 transition text-sm font-medium">+ Añadir Ítem</button>
                    </div>
                    {/* Resumen de totales */}
                    <div className="w-full flex flex-col items-end mt-8">
                        <div className="w-full max-w-md bg-muted/30 rounded-lg p-4">
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-muted-foreground">Subtotal</span>
                                <span className="font-mono">{subtotal.toLocaleString('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 })}</span>
                            </div>
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-muted-foreground">Descuento (%)</span>
                                <input
                                    type="number"
                                    min={0}
                                    max={100}
                                    value={discount}
                                    onInput={e => {
                                        let value = (e.target as HTMLInputElement).value;
                                        // Eliminar todos los ceros a la izquierda
                                        value = value.replace(/^0+(?!$)/, '');
                                        // Sobrescribir el valor del input para evitar que el usuario vea ceros a la izquierda
                                        (e.target as HTMLInputElement).value = value;
                                        if (value === '') {
                                            setDiscount(0);
                                        } else {
                                            const num = Number(value);
                                            if (!isNaN(num) && num >= 0 && num <= 100) {
                                                setDiscount(num);
                                            }
                                        }
                                    }}
                                    onKeyDown={e => {
                                        // Bloquear letras, e, +, - y .
                                        if (["e", "E", "+", "-", "."].includes(e.key)) {
                                            e.preventDefault();
                                        }
                                    }}
                                    className="w-20 rounded border px-2 py-1 bg-background text-right"
                                />
                            </div>
                            <div className="flex justify-between items-center mb-2">
                                <span className="text-muted-foreground">Impuestos (%)</span>
                                <input
                                    type="number"
                                    min={0}
                                    max={100}
                                    value={tax}
                                    onInput={e => {
                                        let value = (e.target as HTMLInputElement).value;
                                        // Eliminar todos los ceros a la izquierda
                                        value = value.replace(/^0+(?!$)/, '');
                                        // Sobrescribir el valor del input para evitar que el usuario vea ceros a la izquierda
                                        (e.target as HTMLInputElement).value = value;
                                        if (value === '') {
                                            setTax(0);
                                        } else {
                                            const num = Number(value);
                                            if (!isNaN(num) && num >= 0 && num <= 100) {
                                                setTax(num);
                                            }
                                        }
                                    }}
                                    onKeyDown={e => {
                                        // Bloquear letras, e, +, - y .
                                        if (["e", "E", "+", "-", "."].includes(e.key)) {
                                            e.preventDefault();
                                        }
                                    }}
                                    className="w-20 rounded border px-2 py-1 bg-background text-right"
                                />
                            </div>
                            <div className="flex justify-between items-center border-t pt-3 mt-3">
                                <span className="font-semibold text-lg">Total</span>
                                <span className="font-bold text-primary text-lg">{total.toLocaleString('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 })}</span>
                            </div>
                        </div>
                    </div>
                    <div className="w-full flex justify-end space-x-4 mt-4">
                        <button type="button" onClick={() => router.visit('/quotes')} className="mt-6 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600 transition w-full sm:w-auto">
                            Cancelar
                        </button>
                        <button type="submit" disabled={processing} className="mt-6 px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition w-full sm:w-auto">
                        {processing ? 'Creando...' : 'Crear Cotización'}
                    </button>
                    </div>
                </form>
            </div>
        </AppLayout>
    )
}

export default CreateQuote
